server:
  port: 8888

spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression:  "'lb://' + serviceId"
      # 路由配置项，对应 RouteDefinition 数组
      routes:
      - id: provider # 路由的编号
        uri: lb://nacos-provider        # 路由到的目标地址
        predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
        - Path=/provider/**
        filters:
        - RewritePath=/provider/(?<remaining>.*), /${remaining}
    nacos:
      discovery:
        server-addr: 47.108.95.152:8848
        namespace: fc68e2b9-83b8-4338-9fc2-af89ef6e0437
  application:
    name: chen-gateway